import { Workspace, User, Task, Expense, ActivityItem, StickyNote, VirtualCard, TrelloList } from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_1',
    name: 'Alex Rivera',
    email: 'alex@synk.app',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Owner',
    status: 'online',
    customStatus: 'Reviewing Q3 Financials 📈',
    currentActivity: 'Viewing Treasury Balance',
    color: '#84cc16',
  },
  {
    id: 'user_2',
    name: 'Sarah Chen',
    email: 'sarah@synk.app',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'Admin',
    status: 'focusing',
    customStatus: 'Sprint Trello planning ⚡',
    currentActivity: 'Editing Trello Board',
    color: '#7c3aed',
  },
  {
    id: 'user_3',
    name: 'Marcus Vance',
    email: 'marcus@synk.app',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Member',
    status: 'online',
    customStatus: 'Designing virtual cards 🎨',
    currentActivity: 'Adding Sticky Memo',
    color: '#0ea5e9',
  },
  {
    id: 'user_4',
    name: 'Elena Rostova',
    email: 'elena@synk.app',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Admin',
    status: 'meeting',
    customStatus: 'Investor Treasury Sync 💼',
    currentActivity: 'Splitting Expenses',
    color: '#a855f7',
  },
  {
    id: 'user_5',
    name: 'David Kim',
    email: 'david@synk.app',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Viewer',
    status: 'away',
    customStatus: 'AFK for tea ☕',
    currentActivity: 'Offline',
    color: '#64748b',
  },
];

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws_1',
    name: 'synk Studio & Collective',
    slug: 'synk-studio',
    logo: '⚡',
    color: '#84cc16',
    plan: 'Pro',
    createdAt: '2026-01-15T08:00:00.000Z',
    memberCount: 5,
    totalCapital: 1500000, // ₹15,00,000 INR
    monthlyBudget: 250000, // ₹2,50,000 INR / month
    joinCode: 'SYNK2026',
  },
  {
    id: 'ws_2',
    name: 'HyperScale AI Collective',
    slug: 'hyperscale-ai',
    logo: '🧠',
    color: '#7c3aed',
    plan: 'Enterprise',
    createdAt: '2026-03-01T09:30:00.000Z',
    memberCount: 8,
    totalCapital: 5000000,
    monthlyBudget: 800000,
    joinCode: 'SCALE99',
  },
];

export const INITIAL_TRELLO_LISTS: TrelloList[] = [
  { id: 'list_ideas', title: '💡 Ideas & Backlog', colorDot: 'bg-slate-400' },
  { id: 'list_todo', title: '⚡ To Do', colorDot: 'bg-indigo-500' },
  { id: 'list_inprogress', title: '🔥 In Progress', colorDot: 'bg-amber-500' },
  { id: 'list_review', title: '👀 Review', colorDot: 'bg-purple-500' },
  { id: 'list_done', title: '✅ Done', colorDot: 'bg-lime-500' },
  { id: 'list_finance', title: '💰 Finance & Invoices', colorDot: 'bg-emerald-500' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    workspaceId: 'ws_1',
    listId: 'list_inprogress',
    title: 'Architect UPI & Multi-Currency Treasury Engine',
    description: 'Implement real-time balance calculations, automated per-member invoice splitting, and instant RuPay/Visa card limits.',
    notepadNotes: `# Treasury Architecture Notes\n- Integrate instant UPI settlement (0% FX spread)\n- Add automated push notification when split is paid\n- Support Apple Pay & RuPay virtual cards`,
    status: 'In Progress',
    priority: 'Urgent',
    colorLabel: 'lime',
    budgetAmount: 45000, // ₹45,000
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    assignees: [INITIAL_USERS[0], INITIAL_USERS[1]],
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['Treasury', 'Backend', 'UPI'],
    subtasks: [
      { id: 'st_1', title: 'Draft RLS policies for organizational wallets', completed: true },
      { id: 'st_2', title: 'Setup WebSocket presence heartbeat for card activity', completed: true },
      { id: 'st_3', title: 'Test UPI QR code generator for team invoices', completed: false },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_2',
    workspaceId: 'ws_1',
    listId: 'list_review',
    title: 'Virtual Card 3D Rendering & NFC Controls',
    description: 'Design the purple virtual card (#3430 4563 7710 7031) with Apple subscription tag and instant freeze/unfreeze.',
    notepadNotes: `# Virtual Card Design Specs\n- Gradient from Purple to Violet\n- Include NFC wave icon and chip illustration\n- Subscriptions badge: ₹4,200/mo Apple iCloud`,
    status: 'Review',
    priority: 'High',
    colorLabel: 'purple',
    budgetAmount: 18500, // ₹18,500
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&auto=format&fit=crop&q=80',
    assignees: [INITIAL_USERS[2]],
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['Cards', 'UI/UX', 'Figma'],
    subtasks: [
      { id: 'st_4', title: 'Create 3D card tilt effect on hover', completed: true },
      { id: 'st_5', title: 'Add copy card number with 1-click', completed: true },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_3',
    workspaceId: 'ws_1',
    listId: 'list_todo',
    title: 'Cashflow In & Out Ledger with Receipt OCR Preview',
    description: 'Filterable data table with Money IN (Income) vs Money OUT (Spend) attribution and receipt image attachments.',
    notepadNotes: `Receipts need zoom controls and instant team reimbursement verification badge.`,
    status: 'To Do',
    priority: 'High',
    colorLabel: 'blue',
    budgetAmount: 32000,
    assignees: [INITIAL_USERS[0], INITIAL_USERS[3]],
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['Finance', 'Ledger', 'OCR'],
    subtasks: [
      { id: 'st_7', title: 'Design receipt viewer modal with zoom', completed: false },
      { id: 'st_8', title: 'Implement split payment math with reimbursement state', completed: false },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_4',
    workspaceId: 'ws_1',
    listId: 'list_done',
    title: 'Instant Command Bar (Cmd+K) Universal Search',
    description: 'Fast search across Trello cards, sticky notepad memos, expenses, and team presence.',
    status: 'Completed',
    priority: 'Medium',
    colorLabel: 'slate',
    assignees: [INITIAL_USERS[1]],
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['Search', 'Shortcuts'],
    subtasks: [
      { id: 'st_10', title: 'Register global keyboard listeners', completed: true },
      { id: 'st_11', title: 'Categorize search results with icons', completed: true },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task_5',
    workspaceId: 'ws_1',
    listId: 'list_finance',
    title: 'Settle Annual Corporate Franchise & Compliance Filing',
    description: 'Annual corporate registered agent fee and legal compliance verification.',
    status: 'Finance & Invoices',
    priority: 'Urgent',
    colorLabel: 'rose',
    budgetAmount: 18000,
    assignees: [INITIAL_USERS[3]],
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['Compliance', 'Legal', 'Operations'],
    subtasks: [
      { id: 'st_13', title: 'Submit proof of UPI / NetBanking payment', completed: true },
      { id: 'st_14', title: 'Archive tax return receipt', completed: false },
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_STICKY_NOTES: StickyNote[] = [
  {
    id: 'note_1',
    workspaceId: 'ws_1',
    title: '💡 Product Sprint Priorities',
    content: `1. Ensure Trello board cards have direct budget tags (₹ amount)
2. Connect Team Notepad with instant live Markdown auto-save
3. Keep single-page workspace ultra fast and responsive!`,
    color: 'yellow',
    isPinned: true,
    author: INITIAL_USERS[0],
    updatedAt: new Date().toISOString(),
    tags: ['Sprint', 'Product'],
  },
  {
    id: 'note_2',
    workspaceId: 'ws_1',
    title: '💰 Q3 Capital Allocation Memo',
    content: `- Liquid Treasury Buffer: ₹9,82,328 active buffer (₹15L seed total)
- Max monthly burn limit: ₹2,50,000
- Keep all software subscriptions on the Purple Apple Card (₹4,200/mo iCloud + Figma)`,
    color: 'mint',
    isPinned: true,
    author: INITIAL_USERS[3],
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    tags: ['Treasury', 'Budget'],
  },
  {
    id: 'note_3',
    workspaceId: 'ws_1',
    title: '🎨 synk Visual Principles',
    content: `- Soft pastel cards (#EDE9FE, #DCFCE7, #E0F2FE)
- Floating Lime Balance Pill Card (₹9,82,328)
- 3D Virtual Cards with card numbers
- Crisp Plus Jakarta Sans typography`,
    color: 'lavender',
    isPinned: false,
    author: INITIAL_USERS[2],
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    tags: ['Design', 'Tokens'],
  },
  {
    id: 'note_4',
    workspaceId: 'ws_1',
    title: '⚡ Growth Experiment Checklist',
    content: `- [x] Product Hunt featured launch
- [x] Twitter / X thread on collaborative Trello + FinTech
- [ ] Creator collective outreach (10 teams)
- [ ] Referral credit bonus (₹1,500 per invited member)`,
    color: 'sky',
    isPinned: false,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
    author: INITIAL_USERS[1],
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    tags: ['Growth', 'Marketing'],
  },
];

export const INITIAL_VIRTUAL_CARDS: VirtualCard[] = [
  {
    id: 'card_1',
    name: 'Apple iCloud & Subscriptions',
    brand: 'Apple',
    cardHolder: 'Alex Rivera',
    cardNumber: '3430 4563 7710 7031',
    expiry: '08/29',
    color: 'purple',
    subscriptionMonthly: 4200, // ₹4,200/mo
    subscriptionService: 'Apple / iCloud',
    balance: 42000,
    limit: 150000,
  },
  {
    id: 'card_2',
    name: 'Corporate Liquid Treasury',
    brand: 'RuPay',
    cardHolder: 'synk Collective',
    cardNumber: '4929 8812 3049 9823',
    expiry: '12/30',
    color: 'lime',
    balance: 982328,
    limit: 2500000,
  },
  {
    id: 'card_3',
    name: 'Marketing & Ad Spend',
    brand: 'Mastercard',
    cardHolder: 'Sarah Chen',
    cardNumber: '5241 6620 9012 3344',
    expiry: '04/28',
    color: 'blue',
    balance: 85000,
    limit: 500000,
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  // Money IN (Inflow / Income / Funding)
  {
    id: 'exp_in_1',
    workspaceId: 'ws_1',
    type: 'IN',
    title: 'Client Retainer — Apex Design Studio Q3',
    amount: 350000.00, // ₹3,50,000
    currency: 'INR',
    category: 'Income / Funding',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    paidBy: INITIAL_USERS[0],
    paymentMethod: 'Wire Transfer',
    status: 'Paid',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    notes: 'Q3 product design & engineering milestone advance payment.',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp_in_2',
    workspaceId: 'ws_1',
    type: 'IN',
    title: 'Angel Capital Injection — Batch #4',
    amount: 1000000.00, // ₹10,00,000
    currency: 'INR',
    category: 'Income / Funding',
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    paidBy: INITIAL_USERS[3],
    paymentMethod: 'Wire Transfer',
    status: 'Paid',
    notes: 'Pre-seed round capital tranche.',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Money OUT (Outflow / Expenses)
  {
    id: 'exp_out_1',
    workspaceId: 'ws_1',
    type: 'OUT',
    title: 'AWS & Supabase Dedicated Cluster Scaling',
    amount: 42000.00, // ₹42,000
    currency: 'INR',
    category: 'Software & AI',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    paidBy: INITIAL_USERS[1],
    paymentMethod: 'UPI / GPay',
    status: 'Paid',
    receiptUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    notes: 'Monthly database cluster and WebSocket connections.',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp_out_2',
    workspaceId: 'ws_1',
    type: 'OUT',
    title: 'Product Hunt Launch & Community Ad Boosts',
    amount: 68000.00, // ₹68,000
    currency: 'INR',
    category: 'Marketing & Ads',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    paidBy: INITIAL_USERS[0],
    paymentMethod: 'Corporate Card',
    status: 'Paid',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=80',
    splits: [
      { userId: 'user_1', userName: 'Alex Rivera', userAvatar: INITIAL_USERS[0].avatar, amount: 34000, paid: true },
      { userId: 'user_4', userName: 'Elena Rostova', userAvatar: INITIAL_USERS[3].avatar, amount: 34000, paid: true },
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp_out_3',
    workspaceId: 'ws_1',
    type: 'OUT',
    title: 'Figma Organization & Adobe Creative Cloud',
    amount: 18500.00, // ₹18,500
    currency: 'INR',
    category: 'Software & AI',
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    paidBy: INITIAL_USERS[2],
    paymentMethod: 'Apple Pay',
    status: 'Reimbursed',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp_out_4',
    workspaceId: 'ws_1',
    type: 'OUT',
    title: 'Apple iCloud & Developer License (Monthly)',
    amount: 4200.00, // ₹4,200
    currency: 'INR',
    category: 'Software & AI',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    paidBy: INITIAL_USERS[0],
    paymentMethod: 'Apple Pay',
    status: 'Paid',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act_1',
    workspaceId: 'ws_1',
    user: INITIAL_USERS[0],
    action: 'logged_expense',
    targetTitle: 'Client Retainer (+₹3,50,000.00)',
    targetType: 'expense',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    details: 'Money IN recorded to treasury',
  },
  {
    id: 'act_2',
    workspaceId: 'ws_1',
    user: INITIAL_USERS[1],
    action: 'completed_task',
    targetTitle: 'Command Bar (Cmd+K) Universal Search',
    targetType: 'task',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    details: 'Moved to Done on Trello Board',
  },
  {
    id: 'act_3',
    workspaceId: 'ws_1',
    user: INITIAL_USERS[0],
    action: 'logged_expense',
    targetTitle: 'AWS & Supabase (-₹42,000.00)',
    targetType: 'expense',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    details: 'Money OUT via UPI',
  },
];
